### ISSUE TITLE
how do i run this on my website

### ISSUE THREAD

**Issue by Blubaugh09** [yandeu/phaser3-typescript-platformer-example#1]
I tried to download your files and extract them in my file management system for a subdomain to test because i want to fork what you have for a game i want to create. its fantastic! but all i get is a black screen? besides unzipping it is there something in the code i need to change?

Your framework is perfect and i have been struggling to get mobile controls to work like you did in your example.

**Comment by yandeu** [comment]
You have to [follow these steps](https://github.com/yandeu/phaser-project-template#how-to-use) to build a production ready code to the /dist folder which you can then put on your server.

I have just added a [how to use section](https://github.com/yandeu/phaser3-typescript-platformer-example#how-to-use) in the project.

**Comment by Blubaugh09** [comment]
Great Thanks! 😀
